### ISSUE TITLE
Accept third boolean argument in toggleModifier

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/bem.js#9]
Similarly to `node.classList.toggle('some-class', some_condition)`, I'd like to be able to do

```javascript
BEM.toggleModifier(node, 'bar', some_condition);
```

This removes boilerplate such as

```javascript
if (some_condition) {
    BEM.addModifier(node, 'bar');
} else {
    BEM.removeModifier(node, 'bar');
}
```

**Comment by svenvandescheur** [comment]
Please note that we can't rely on node.classList.toggle as the seconds argument is not support by Internet Explorer. See: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList.

**Comment by sergei-maertens** [comment]
could be just syntactic sugar, as I'm now doing this:

```javascript
const toggleDisabled = function(node, shouldBeDisabled) {
    const modifier = 'disabled';
    if (Boolean(shouldBeDisabled)) {
        BEM.addModifier(node, modifier);
    } else {
        BEM.removeModifier(node, modifier);
    }
};
```

**Comment by svenvandescheur** [comment]
Will probably be implemented something like that. The current implementation relies on a fixe hasModifier check:

```js
    static toggleModifier(node, modifier) {
        if (BEM.hasModifier(node, modifier)) {
            BEM.removeModifier(node, modifier);
            return;
        }
        BEM.addModifier(node, modifier);
    }
```

The if statement can be populated with an expression which defaults to hasModifier...

**Comment by svenvandescheur** [comment]
This was resolve in #10 .
